version: '3.7'

services:
  mongodb:
    image: mongo:4.0.3-xenial
    environment:
      - MONGO_DATA_DIR=/data/db
      - ENV=production
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: ["mongod", "--smallfiles"]
  web:
    build: .
    links:
      - mongodb
    container_name: server.js
    environment: 
      - ENV=production
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    restart: always
